name: Scheduled Weather Data Ingestion

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  run_data_ingestion:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Run Weather Scraper and Database Update
        run: python data_integration/integrate_data.py
        
      - name: Commit Database Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          files: 'data/weather_db.sqlite'
          commit_message: '🤖 Scheduled data ingestion update [skip ci]'
          branch: main
